version: '3'

services:
  api:
    container_name: api
    build: .
    restart: always
    ports:
     - 8000
    environment:
      SERVER_PORT: 8000
      REDIS_SERVER: redis
    depends_on:
      - redis

  redis:
    container_name: cache
    image: "redis:alpinelinux"
